context:
  version: "2.23.0"

package:
  name: libosmium
  version: ${{ version }}

source:
  - url: https://github.com/osmcode/libosmium/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 2e7a4ab34a80843490a1d673811d600e5445e6d39a0cfc42609d0861eba24669

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja

  host:
    - libboost-devel
    - expat
    - lz4-c
    - protozero
    - bzip2
    - zlib

tests:
  - package_contents:
      include:
        - osmium/version.hpp

about:
  homepage: https://osmcode.org/libosmium/
  license: BSL-1.0
  license_file:
    - LICENSE
  summary: Fast and flexible C++ library for working with OpenStreetMap data.
  description: |
    The Osmium Library has extensive support for all types of OSM entities: nodes, ways, relations, 
    and changesets. It allows reading from and writing to OSM files in XML, PBF, and several other
    formats, including change files and full history files.
  documentation: https://github.com/mapbox/libosmium
  repository: https://github.com/mapbox/libosmium

extra:
  recipe-maintainers:
    - travishathaway
